### ISSUE TITLE
 Error while calling lua chunk.

### ISSUE THREAD

**Issue by Teeheey** [rafcamlet/nvim-whid#1]
Hi there!
Copied your plugin to my dotfiles to test
And got an error while calling Whid command

<path_to_my_code.lua>:68: attempt to index field 'fn' (a nil value)

NVIM v0.4.3

macOS Catalina
Version: 10.15.2

I was thinking, that this is because I have no changes in my git directory
Jumped to project, where I haven't committed yet - same behaviour

If I run command
`git diff-tree --no-commit-id --name-only -r  HEAD~` in this directory - some tracked files will be returned.

**Comment by rafcamlet** [comment]
It seems `vim.fn` is introduced in current pre-release build (02.2020). You can use 
```local result = vim.api.nvim_call_function('systemlist', {'git diff-tree --no-commit-id --name-only -r  HEAD~'..position})``` instead.

https://github.com/rafcamlet/nvim-whid/commit/a49c6998aaa847c97a5a43e66da832517d83bc87
